FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build


# ===========================
# 2) Servidor Nginx (producción)
# ===========================
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

# Copia un archivo de configuración nginx si necesitas rewrites
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
